#!/bin/bash
# Compile script for dynlib

# Obs: The order of the files in $files has to reflect the interdepencies!
files='dynlib_config.f95 dynlib_diag.f95' 
filek='dynlib_kind.f95'
pysig='dynlib.pyf'

# 1. Creating new python signature file
echo "Stage 1: Creating python signature file"
rm $pysig
f2py -m dynlib -h $pysig $files > /dev/null
sed "s/\<nr\>/8/g" dynlib.pyf | sed "s/\<ni\>/4/g" > ${pysig}_tmp
mv ${pysig}_tmp $pysig

# 2. Compiling the fortran modules 
echo "Stage 2: Creating Fortran *.mod files"
gfortran -c $filek $files

# 3. Compiling the shared object usable from within python
echo "Stage 3: Compiling the python module (as a shared object)"
f2py -c --fcompiler=gnu95 dynlib.pyf $files $filek > /dev/null

#
